version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80" # React build served on localhost:3000
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:8080" # .NET API exposed on localhost:5000
