[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[variables]
DOTNET_ROOT = "/app/server"

[phases.install]
cmds = ["dotnet restore ./server/server.csproj"]

[phases.build]
cmds = ["dotnet publish ./server/server.csproj -c Release -o out"]

[start]
cmd = "dotnet ./out/server.dll"
