[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore ./server.csproj"]

[phases.build]
cmds = ["dotnet publish ./server.csproj -c Release -o out"]

[start]
cmd = "dotnet ./out/server.dll"
